Repository Mission-DMX/Project-Editor, pull requests merged in 2024-04, with the labels that each got.

#125 fix: show file serialization
  src/controller/file/read.py
  src/controller/file/serializing/filter_serialization.py
  src/controller/file/serializing/fish_optimizer.py
  src/controller/file/serializing/general_serialization.py
  src/controller/file/serializing/scene_serialization.py
  src/controller/file/transmitting_to_fish.py
  src/controller/file/write.py
  src/controller/utils/process_notifications.py
  src/view/main_window.py
  src/view/show_mode/editor/show_browser/show_browser.py
Labels: bug

#128 fix: auto show commit on preview
  src/view/show_mode/editor/node_editor_widgets/cue_editor/cue_editor_widget.py
  src/view/show_mode/editor/nodes/type_to_node_dict.py
Labels: bug

#116 Pan tilt constant vfilter
  README.md
  requirements.txt
  src/controller/cli/joystick_enum.py
  src/controller/cli/joystick_handling.py
  src/main.py
  src/model/broadcaster.py
  src/model/filter.py
  src/model/virtual_filters/__init__.py
  src/model/virtual_filters/pan_tilt_constant.py
  src/view/show_mode/editor/filter_settings_item.py
  src/view/show_mode/editor/node_editor_widgets/cue_editor/cue_editor_widget.py
  src/view/show_mode/editor/node_editor_widgets/pan_tilt_constant/__init__.py
  src/view/show_mode/editor/node_editor_widgets/pan_tilt_constant/pan_tilt_constant_content_widget.py
  src/view/show_mode/editor/node_editor_widgets/pan_tilt_constant/pan_tilt_constant_widget.py
  src/view/show_mode/editor/nodes/filter_node_library.py
  src/view/show_mode/editor/nodes/impl/constants.py
  src/view/show_mode/editor/nodes/type_to_node_dict.py
  src/view/show_mode/editor/show_ui_widgets/__init__.py
  src/view/show_mode/editor/show_ui_widgets/cue_control.py
  src/view/show_mode/editor/show_ui_widgets/pan_tilt_constant_show_ui.py
Labels: enhancement

#132 Various cue editor improvements
  src/model/virtual_filters/auto_tracker_filter.py
  src/view/show_mode/editor/filter_settings_item.py
  src/view/show_mode/editor/node_editor_widgets/cue_editor/channel_label.py
  src/view/show_mode/editor/node_editor_widgets/cue_editor/cue_editor_widget.py
  src/view/show_mode/editor/node_editor_widgets/cue_editor/timeline_content_widget.py
  src/view/show_mode/editor/node_editor_widgets/cue_editor/timeline_editor.py
  src/view/show_mode/editor/nodes/impl/effects.py
  src/view/show_mode/editor/show_ui_widgets/__init__.py
  src/view/show_mode/editor/show_ui_widgets/cue_control.py
Labels: bug, enhancement

#134 Improve CLI functionality
  src/controller/cli/cli_context.py
  src/controller/cli/command.py
  src/controller/cli/help_command.py
  src/controller/cli/list_command.py
  src/controller/cli/remote_control_port.py
  src/controller/cli/select_command.py
  src/controller/cli/show_command.py
  src/main.py
  src/network.py
  src/view/main_window.py
  src/view/show_mode/editor/node_editor_widgets/cue_editor/cue_editor_widget.py
  src/view/show_mode/editor/show_browser/fixture_to_filter.py
  src/view/show_mode/editor/show_ui_widgets/cue_control.py
Labels: enhancement

#143 Fix vfilter univ consolidation
  src/controller/file/serializing/fish_optimizer.py
Labels: bug
